version: "3"

services:
  app:
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py createsuperuser --noinput &&
             python3 manage.py runserver 0.0.0.0:8000"
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/app
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - "5432:5432"
volumes:
  postgres_data: