# Generated by Django 5.0.4 on 2024-04-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_collection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='url_type',
            field=models.CharField(max_length=100),
        ),
    ]
