# Generated by Django 5.0.4 on 2024-04-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_container_url_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='title',
            field=models.TextField(),
        ),
    ]
